[env:esp32-s3-display]
platform = espressif32
board = esp32s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags = 
  -DLV_CONF_INCLUDE_SIMPLE
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
  lvgl/lvgl@^9.1.0
  lvgl/lv_drivers
